In [12]:
import torch
from torchvision.io.image import read_image
from torchvision.models.detection import fasterrcnn_resnet50_fpn_v2, FasterRCNN_ResNet50_FPN_V2_Weights
from torchvision.utils import draw_bounding_boxes
from torchvision.transforms.functional import to_pil_image
import os
import cv2

In [ ]:
weights = FasterRCNN_ResNet50_FPN_V2_Weights.DEFAULT
model = fasterrcnn_resnet50_fpn_v2(weights = weights, box_score_thresh = 0.8)
model.eval()
preprocess = weights.transforms()

input_folder = 'frames'
output_folder = 'pretrained_teacher'
os.makedirs(output_folder, exist_ok = True)

for filename in os.listdir('frames'):
    if filename.endswith('.jpg'):
        input_image_path = os.path.join(input_folder, filename)
        img = read_image(input_image_path)
        img_tensor = preprocess(img).unsqueeze(0)

        with torch.no_grad():
            prediction = model(img_tensor)

        output = img.clone().squeeze(0)
        output = draw_bounding_boxes(output, 
                                        boxes = prediction[0]['boxes'],
                                        colors = "red")
        output_image_path = os.path.join(output_folder, filename)
        to_pil_image(output).save(output_image_path)
        
        


In [24]:
# player detection with blob
n_im = 10
images = read_image('field_frames/00000.jpg')
field_path = 'field_frames'
path_segs = 0
score_thresh = 0.8
avg_bbox_dims = [0.5, 0.5]
prop_avg = 0.5

# n_im = len(frame_files)

output_detections = []
output_scores = []
seg_bbox_list_list = []

for f in range(n_im):
    field_in = cv2.imread(os.path.join(field_path, str(f).zfill(5) + '.jpg'))
    seg_bbox_list = player_segmentation(field_in, avg_bbox_dims, prop_avg)
    seg_bbox_list = torch.tensor(seg_bbox_list).type(torch.FloatTensor)
    scores = torch.tensor([1.]*len(seg_bbox_list))
    


[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 63 126  84]
  [ 63 126  84]
  [ 63 126  84]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 66 126  85]
  [ 66 126  85]
  [ 66 126  85]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 66 126  85]
  [ 66 126  85]
  [ 66 126  85]]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..